var util = require('util');
var session_c = require('./session_c');
var school_m = require('../model/school_m');
var School = (function () {
//添加学校
function add_School(req,res,next){
    school_m.add_School(req.body,function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                res.json({
                    success:0,
                    desc:"success",
                    data:{}
                })
            }
        });  
   }
//修改学校
function modify_School(req,res,next){
    var id=req.params.id;
    school_m.modify_School(id,req.body,function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                res.json({
                    success:0,
                    desc:"success",
                    data:{}
                })
            }
        });  
   }
 //删除学校
function delete_School(req,res,next){
    var id=req.params.id;
    school_m.delete_School(id,function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                res.json({
                    success:0,
                    desc:"success",
                    data:{}
                })
            }
        });  
   }  
 //获取学校列表
function get_Schoollist(req,res,next){
    school_m.get_Schoollist(function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                if(result==""||result==null){
                    res.json({
                        success:0,
                        desc:"success",
                        data:{}
                    })
                }else{
                    console.log(result);
                    res.json({
                        success:0,
                        desc:"success",
                        data:{
                            School_List:result.map(function(elem){
                                return{
                                    id:elem.id,
                                    school_name:elem.school_name,
                                    school_position:elem.school_position,
                                    long_latitude_range:elem.long_latitude_range,
                                    phone:elem.username,
                                    name:elem.name
                                }
                            })
                        }
                    })
               }
            }
        });  
   }  
   //小程序测试
function get_Schoollist_small(req,res,next){
    res.json({
        success:"0",
        data:{
            name:"钱明一",
            age:"25"
        }
    })
   }  
   //条件查询学校列表
function query_Schoollist(req,res,next){
    school_m.query_Schoollist(req.body,function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                if(result==""||result==null){
                    res.json({
                        success:0,
                        desc:"success",
                        data:{}
                    })
                }else{
                    res.json({
                        success:0,
                        desc:"success",
                        data:{
                            School_List:result.map(function(elem){
                                return{
                                    id:elem.id,
                                    school_name:elem.school_name,
                                    school_position:elem.school_position,
                                    long_latitude_range:elem.long_latitude_range,
                                    phone:elem.username,
                                    name:elem.name
                                }
                            })
                        }
                    })
               }
            }
        });  
   } 
   //修改学校+经纬度
function modify_school_Long_latitude(req,res,next){
    var id=req.params.id;
    school_m.modify_school_Long_latitude(id,req.body,function(err,result){
            if(err){
                console.log("err"+err);
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                console.log("success"+result);
                res.json({
                    success:0,
                    desc:"success",
                    data:{}
                })
            }
        });  
   }
//根据学校的id查询经纬度
function get_school_Long_latitude(req,res,next){
    var school_id=req.params.id;
    school_m.get_school_Long_latitude(school_id,function(err,result){
            if(err){
                res.json({
                    success:-1,
                    desc:"fail",
                    data:{}
                })
            }else{
                if(result==""||result==null){
                    res.json({
                        success:1,
                        desc:"没有该学校",
                        data:{

                        }
                    })
                }else{
                    res.json({
                        success:0,
                        desc:"success",
                        data:{
                            id:result.id, 
                            long_latitude_range:result.long_latitude_range
                        }
                    })
               }
            }
        });  
   } 
       return {
        add_School:add_School,
        modify_School:modify_School,
        delete_School:delete_School,
        get_Schoollist:get_Schoollist,
        query_Schoollist:query_Schoollist,
        modify_school_Long_latitude:modify_school_Long_latitude,
        get_Schoollist_small:get_Schoollist_small,
        get_school_Long_latitude:get_school_Long_latitude
    };
})();

module.exports = exports = School;